# F1 Scraper - Debug Workflow
# ===========================
# Use this workflow to debug issues

name: Debug F1 Scraper

on:
  workflow_dispatch:  # Only run manually
  
jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Check Python version
      run: |
        python --version
        pip --version

    - name: List files
      run: |
        echo "📁 Repository contents:"
        ls -la
        echo ""
        echo "📄 Python files:"
        find . -name "*.py" -type f

    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Test Python syntax
      run: |
        echo "🔍 Checking Python syntax..."
        python -m py_compile f1_scraper_pro.py
        echo "✅ Syntax check passed"

    - name: Test imports
      run: |
        echo "📦 Testing imports..."
        python -c "
        import requests
        import bs4
        import lxml
        print('✅ All core dependencies imported successfully')
        "

    - name: Test scraper import
      run: |
        echo "🏎️ Testing scraper import..."
        python -c "
        try:
            from f1_scraper_pro import F1ResultsScraperPro
            print('✅ Scraper imported successfully')
            scraper = F1ResultsScraperPro(year=2024)
            print(f'✅ Scraper initialized: {scraper.base_url}')
        except Exception as e:
            print(f'❌ Error: {e}')
            import traceback
            traceback.print_exc()
        "

    - name: Test network connectivity
      run: |
        echo "🌐 Testing network connectivity..."
        python -c "
        import requests
        try:
            response = requests.get('https://www.formula1.com', timeout=10)
            print(f'✅ F1 website accessible: {response.status_code}')
        except Exception as e:
            print(f'❌ Network error: {e}')
        "

    - name: Run troubleshooting script (if exists)
      continue-on-error: true
      run: |
        if [ -f "troubleshoot.py" ]; then
          echo "🔧 Running troubleshooting script..."
          python troubleshoot.py
        else
          echo "ℹ️ No troubleshooting script found"
        fi

    - name: Summary
      run: |
        echo "🏁 Debug Summary"
        echo "================"
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Working directory: $(pwd)"
        echo "Available space: $(df -h . | tail -1 | awk '{print $4}')"
        echo ""
        echo "If this debug workflow passes, the main workflow should work too."
        echo "Check the logs above for any errors."